version: '3.9'
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./d–∞ta:/root/redis
    environment:
      - REDIS_PASSWORD=asdfghjkl
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - default
  

  operator-server:
    build:
      dockerfile: dockerfile
    ports:
      - 8000:8000
    restart: always
    environment:
      - REDIS_HOST
      - PHOTO_MAIN_FOLDER
      - FAKE_DATA_ROOT
      - YOLO_MODEL_PATH
      - BOTTOM_CLASSIF_MODEL_PATH
      - SIDE_CLASSIF_MODEL_PATH
      - PACKET_CLASSIF_MODEL_PATH
      - MODELS_PATH
      - COMPILED
    volumes:
      - ./testfolder:/home/data
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://operator-server:8000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 3s


  sideclient:
    build:
      context: fm
      dockerfile: dockerfile
    depends_on:
      operator-server:
        condition: service_healthy
    restart: always
    environment:
      - WS_CONTROL_URL
    networks:
      - default

networks:
  default: